from .centro import Centro
from .curso import Curso
from .coordenacao import Coordenacao
from .professor import Professor
from .disciplina import Disciplina
from .disciplina_professor import DisciplinaProfessor
from .tipo_periodo import TipoPeriodo
from .periodo import Periodo
from .dias_semana import DiasSemana
from .horario_curso import HorarioCurso
from .preferencias import Preferencias
from .horarios_disciplinas import HorariosDisciplinas
