# Generated by Django 5.1 on 2024-09-12 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DiasSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('quantidade_periodos', models.PositiveIntegerField()),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgh_app.centro')),
            ],
        ),
        migrations.CreateModel(
            name='Coordenacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordenacao', to=settings.AUTH_USER_MODEL)),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordenacao', to='sgh_app.curso')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='sgh_app.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='sgh_app.curso')),
                ('tipo_periodo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='sgh_app.tipoperiodo')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='sgh_app.curso')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='sgh_app.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores', to='sgh_app.centro')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores', to='sgh_app.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Preferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_preferidos', models.ManyToManyField(related_name='preferidos', to='sgh_app.diassemana')),
                ('horas_preferidas', models.ManyToManyField(related_name='preferidas', to='sgh_app.horariocurso')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to='sgh_app.professor')),
            ],
        ),
        migrations.CreateModel(
            name='HorariosDisciplinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_disciplinas', to='sgh_app.diassemana')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_disciplinas', to='sgh_app.disciplina')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_disciplinas', to='sgh_app.periodo')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_disciplinas', to='sgh_app.professor')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplina_professores', to='sgh_app.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplina_professores', to='sgh_app.professor')),
            ],
        ),
    ]
