# Generated by Django 5.1 on 2024-09-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgh_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestre',
            name='nome',
            field=models.CharField(choices=[('primeiro_semestre', '1º semestre letivo'), ('segundo_semestre', '2º semestre letivo'), ('dple', 'DPLE')], max_length=50),
        ),
    ]
