# Generated by Django 5.1 on 2024-10-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgh_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariosdisciplinas',
            name='periodo',
            field=models.CharField(blank=True, choices=[('par', 'Par'), ('impar', 'Ímpar')], max_length=5, null=True),
        ),
    ]
