# Generated by Django 5.1 on 2024-09-30 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgh_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariosdisciplinas',
            name='disciplina_professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_disciplinas', to='sgh_app.disciplinaprofessor'),
        ),
    ]
