# Generated by Django 5.1 on 2024-08-29 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgh_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='centro_id',
            new_name='centro',
        ),
        migrations.AddField(
            model_name='curso',
            name='quantidade_periodos',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Coordenacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordenacao', to='sgh_app.curso')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordenacao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
