# Generated by Django 5.1 on 2024-09-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgh_app', '0002_remove_periodo_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='numero',
            field=models.IntegerField(default=1),
        ),
    ]
