# Generated by Django 5.1 on 2024-10-11 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgh_app', '0002_horariosdisciplinas_periodo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='anosemestre',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='anosemestre',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sgh_app.curso'),
        ),
        migrations.AlterUniqueTogether(
            name='anosemestre',
            unique_together={('ano', 'semestre', 'curso')},
        ),
    ]
