# Generated by Django 5.1 on 2024-09-18 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgh_app', '0003_periodo_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='tipo_periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='sgh_app.tipoperiodo'),
        ),
    ]
