# Generated by Django 5.1 on 2024-09-10 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgh_app', '0003_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='centro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='professores', to='sgh_app.centro'),
        ),
    ]
