# Generated by Django 5.1 on 2024-09-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgh_app', '0003_alter_periodo_semestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horariocurso',
            name='hora',
        ),
        migrations.AddField(
            model_name='horariocurso',
            name='hora_fim',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AddField(
            model_name='horariocurso',
            name='hora_inicio',
            field=models.TimeField(default='08:00:00'),
        ),
    ]
