# Generated by Django 5.1 on 2024-10-12 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgh_app', '0003_alter_anosemestre_unique_together_anosemestre_curso_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horariosdisciplinas',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='AlocacaoDisciplinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='sgh_app.disciplinaprofessor')),
                ('horarios_disciplinas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='sgh_app.horariosdisciplinas')),
            ],
        ),
    ]
