# Generated by Django 5.1 on 2024-09-10 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgh_app', '0004_professor_centro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores', to='sgh_app.centro'),
        ),
    ]
