# Generated by Django 5.1 on 2024-10-14 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgh_app', '0004_alter_horariosdisciplinas_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariosdisciplinas',
            name='dia_semana',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sgh_app.diassemana'),
        ),
    ]
