# Generated by Django 5.1 on 2024-09-19 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgh_app', '0004_remove_horariocurso_hora_horariocurso_hora_fim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferencias',
            name='dias_preferidos',
        ),
        migrations.RemoveField(
            model_name='preferencias',
            name='horas_preferidas',
        ),
        migrations.AddField(
            model_name='preferencias',
            name='dia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sgh_app.diassemana'),
        ),
        migrations.AddField(
            model_name='preferencias',
            name='horario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sgh_app.horariocurso'),
        ),
    ]
