# Generated by Django 5.1 on 2024-09-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgh_app', '0004_alter_periodo_tipo_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoperiodo',
            name='nome',
            field=models.CharField(choices=[('impar', '1º semestre letivo'), ('par', '2º semestre letivo'), ('dple', 'DPLE'), ('oferta_especial', 'Oferta Especial')], max_length=50),
        ),
    ]
