# Generated by Django 5.1 on 2024-09-10 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgh_app', '0005_alter_professor_centro'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiasSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='sgh_app.curso')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplina_professores', to='sgh_app.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplina_professores', to='sgh_app.professor')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='sgh_app.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='sgh_app.curso')),
                ('tipo_periodo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='sgh_app.tipoperiodo')),
            ],
        ),
        migrations.CreateModel(
            name='HorariosDisciplinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_disciplinas', to='sgh_app.diassemana')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_disciplinas', to='sgh_app.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_disciplinas', to='sgh_app.professor')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_disciplinas', to='sgh_app.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Preferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_preferidos', models.ManyToManyField(related_name='preferidos', to='sgh_app.diassemana')),
                ('horas_preferidas', models.ManyToManyField(related_name='preferidas', to='sgh_app.horariocurso')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to='sgh_app.professor')),
            ],
        ),
    ]
