# Generated by Django 5.1 on 2024-09-19 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgh_app', '0005_remove_preferencias_dias_preferidos_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preferencias',
            new_name='Preferencia',
        ),
    ]
