# Generated by Django 5.1 on 2024-10-15 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgh_app', '0005_horariosdisciplinas_dia_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariosdisciplinas',
            name='dia_semana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgh_app.diassemana'),
        ),
        migrations.AlterField(
            model_name='horariosdisciplinas',
            name='horario_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_disciplinas', to='sgh_app.horariocurso'),
        ),
        migrations.AlterUniqueTogether(
            name='horariosdisciplinas',
            unique_together={('horario_curso', 'dia_semana', 'periodo')},
        ),
    ]
