# Generated by Django 5.1 on 2024-09-19 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgh_app', '0006_rename_preferencias_preferencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_preferidos', models.ManyToManyField(related_name='preferidos', to='sgh_app.diassemana')),
                ('horas_preferidas', models.ManyToManyField(related_name='preferidas', to='sgh_app.horariocurso')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to='sgh_app.professor')),
            ],
        ),
        migrations.DeleteModel(
            name='Preferencia',
        ),
    ]
