# Generated by Django 5.1 on 2024-10-15 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgh_app', '0006_alter_horariosdisciplinas_dia_semana_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horariosdisciplinas',
            unique_together={('horario_curso', 'dia_semana', 'periodo', 'ano_semestre')},
        ),
    ]
