# Generated by Django 5.1.2 on 2024-10-28 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgh_app', '0007_alter_horariosdisciplinas_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horariosdisciplinas',
            name='disciplina_professor',
        ),
        migrations.AddField(
            model_name='horariosdisciplinas',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_disciplinas', to='sgh_app.curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horariosdisciplinas',
            name='disciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_disciplinas', to='sgh_app.disciplina'),
        ),
    ]
