# Generated by Django 5.1.2 on 2024-11-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgh_app', '0008_remove_horariosdisciplinas_disciplina_professor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariocurso',
            name='is_ativo',
            field=models.BooleanField(default=True),
        ),
    ]
